### ISSUE TITLE
больше не работает ?

### ISSUE THREAD

**Issue by zoldaten** [jekeam/parser_kadarbit#1]

**Comment by jekeam** [comment]
работал, но я его перестал поддерживать уже давно, надо докручивать, я щас уже не вспомню че надо делать чтоб это запустить :D

**Comment by zoldaten** [comment]
Так основной файл kadarbitrcrawlerwithproxy.py. Если оттуда повыкидывать прокси и email уведомления, он все равно не пашет.

**Comment by jekeam** [comment]
больше не работает 😁
